name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: marcintk/ha-shared/.github/workflows/build-and-test.yml@main
    permissions:
      contents: read
      pull-requests: write
