name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-*'

jobs:
  release:
    uses: marcintk/ha-shared/.github/workflows/publish-release.yml@main
    permissions:
      contents: write
